spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/uptime?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

jwt:
  secret: "iamdoomole-fullstack-developer-with-six-years-experience"
  expirationSeconds: 86400
