spring:
  application:
    name: uptime
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: false
        format_sql: true
    open-in-view: false
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000

# application.yml
logging:
  level:
    root: INFO
    com.doomole.uptime.config.log: INFO     # ??/AOP ??? INFO
    com.doomole.uptime.service: INFO
    org.springframework.web: WARN
    reactor.netty.http.client: WARN         # ??? DEBUG? ??? ?? ?? ??


uptime:
  results:
    retentionDays: 30
